### ISSUE TITLE
[Storybook][Docs][Table] Needing to add 'forge-ignore' to checkbox delegates needs improved documentation

### ISSUE THREAD

**Issue by Ross-Blakeney** [tyler-technologies-oss/forge#133]
**Describe the bug:**
Missing/lacking docs.
Needing to add the `forge-ignore` attribute to the checkbox delegate in a column filter is not well documented.

**To Reproduce:**
N/A

**Expected behavior:**
There should be a "common issues" section or something similar to capture hard-to-categorize issues and implementation details like adding the `forge-ignore` to specific delegates. It does seem to be mentioned under the  "selectAllTemplate" property but is not visible or clear enough.

**Screenshots:**
[forge-ignore in table code](https://github.com/tyler-technologies-oss/forge/blob/2c248fa97bdde08103d809096789a69caa26f812/src/lib/table/table-constants.ts#L54-L55)

[Commit showing how to solve](https://github.com/tyler-technologies/tcp-admincenter/pull/82/commits/adf8fbc5bfa599df153d3ddb51a97ed0cc710676)

**Please complete the following information:**
 - Forge version: 2.x
 - I have searched existing issues before creating this report? Y
 - Browser: N/A
 - Platform: N/A
 - OS: N/A

**Additional context:**
No bug. Just a request to revisit docs.

**Comment by DRiFTy17** [comment]
I agree that we should add a note about using `forge-ignore` so developers know what it is and how it's used, but this comes down to being a bug in the table component. A similar issue is noted in #122, and the fix for that should solve this one.

Any `<input type="checkbox">` elements within a custom cell template or a filter cell should be ignored by the table component, and it appears that they are not right now which is incorrect.

I'll likely batch the changes for both of these together in one PR.
