### ISSUE TITLE
Support for Vite / SvelteKit

### ISSUE THREAD

**Issue by milan-gm** [tyler-technologies-oss/forge#252]
**Describe the bug:**

Register the web component in `+layout.svelte`.
``` svelte
<script>
  import { defineDatePickerComponent } from "@tylertech/forge/esm";
  import "../../app.css";

  defineDatePickerComponent();
</script>

<slot />

<forge-date-picker>
  <forge-text-field>
    <input type="text" id="input-date-picker" />
    <label for="input-date-picker">Choose date</label>
  </forge-text-field>
</forge-date-picker>
```

Then I get his error.

``` 
5:08:01 PM [vite-plugin-svelte] ssr compile in progress ...
(node:153151) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading 'defineDatePickerComponent')
```

**Please complete the following information:**
 - Forge version: ^2.13.2
 - I have searched existing issues before creating this report? Y
 - Browser: Chrome
 - Platform: Desktop
 - OS: Linux

**Comment by DRiFTy17** [comment]
Forge is a client-side library that doesn't execute in node because it requires access to browser APIs. This means that you need to configure your SvelteKit application to only import the Forge JavaScript when it's running in a browser environment.

Note: this is true for any Web Component library or third-party library that utilizes browser APIs.

For example, you could so something like this following:
```
<script>
  import { onMount } from 'svelte';

  onMount(async () => {
    await import('@tylertech/forge');
  });
</script>
```

This is noted in the SvelteKit documentation here:
https://kit.svelte.dev/faq#how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window
