### ISSUE TITLE
[forge-expansion-panel] add an option to support not rendering the expanded content until expanded

### ISSUE THREAD

**Issue by conner-fallone** [tyler-technologies-oss/forge#394]
**Describe the feature:**
The forge-expansion-panel should provide an option to not render the expanded content until the expansion panel is actually expanded. In many scenarios, the default behavior may be fine, but in other scenarios where a lot of content might be getting shown in here, it becomes problematic.

**Describe any alternatives you've considered:**
In Angular, we've gotten around this by providing an *ngIf on nested context and "caching" whether or not it's been expanded once or before to persist it in the DOM. There are some qwirks to this though if you want animations to work, since *ngIf could result in animations not working at all. To get around this, we had to *ngIf it in and force change detection in the beforeOpen like so:

```
public beforeOpen = (index: number) => {
    this.expandedCache[index] = true;
    this._changeDetectorRef.detectChanges();
};
```

This ensured that the content to expand was in the DOM before the expansion animation happened.

**Additional context:**
In our specific scenario, we are rendering HTML and working with a data set where customers could have hundreds of expansion panels, each of which could have A LOT of text to parse as HTML.

**Comment by DRiFTy17** [comment]
@conner-fallone I don't believe this is something that the Forge expansion panel can be responsible for unfortunately because it doesn't own/control the DOM you are providing. The same issue exists with the native `<details>` element because it is just controlling when the browser renders your content visibly, but the actual elements are still active in the DOM when collapsed.

Your workaround is something I would expect you to need to do unfortunately, and I understand it is a pain. I've thrown around the idea in the past to create an Angular-specific version of the Forge expansion panel so that it can tie into the lifecycle of Angular to not insert the content into the DOM until _just_ before it is expanded. As you've noted, the content needs to be in the DOM before the animations are triggered since it uses JavaScript to compute the height of the content to expand to dynamically.

Unless I'm misunderstanding, or if you have any suggestions how this may be implemented in a framework-agnostic way, then our hands are tied on this one and we may need to close this issue.

**Comment by conner-fallone** [comment]
> @conner-fallone I don't believe this is something that the Forge expansion panel can be responsible for unfortunately because it doesn't own/control the DOM you are providing. The same issue exists with the native `<details>` element because it is just controlling when the browser renders your content visibly, but the actual elements are still active in the DOM when collapsed.
> 
> Your workaround is something I would expect you to need to do unfortunately, and I understand it is a pain. I've thrown around the idea in the past to create an Angular-specific version of the Forge expansion panel so that it can tie into the lifecycle of Angular to not insert the content into the DOM until _just_ before it is expanded. As you've noted, the content needs to be in the DOM before the animations are triggered since it uses JavaScript to compute the height of the content to expand to dynamically.
> 
> Unless I'm misunderstanding, or if you have any suggestions how this may be implemented in a framework-agnostic way, then our hands are tied on this one and we may need to close this issue.

Agreed that there is probably not much we can do at this level, as I currently do not have any suggestions. Should i open it on the forge-angular repo for further discussion? I do think having this flexibility would be valuable.
