### ISSUE TITLE
sveltekit report error 'Cannot use import statement outside a module'

### ISSUE THREAD

**Issue by shynome** [tyler-technologies-oss/forge#670]
**Describe the bug:**

**To Reproduce:**

1. `npm create svelte@latest fff`
2. `npm install @tylertech/forge -D`
3. replace `src/routes/+page.svelte`

   ```svelte
   <script>
     import { defineButtonComponent, defineCardComponent } from "@tylertech/forge";
     defineButtonComponent();
     defineCardComponent();
   </script>

   <div>
     <forge-card>
       <forge-button>Click me</forge-button>
     </forge-card>
   </div>
   ```

4. `npm run dev`
5. open <http://localhost:5173/>
6. See error

**Expected behavior:**
no error

**Screenshots:**
![image](https://github.com/user-attachments/assets/d1f0de25-4e22-4a0c-9864-a201eb53531b)

**Please complete the following information:**

- Forge version: 3.0.0
- I have searched existing issues before creating this report? [Y/N] Y
- Browser: [e.g. Chrome, Firefox, Safari, All] All
- Platform: [e.g. desktop, mobile, All] All
- OS: [e.g. Windows, Mac, Linux, iOS, Android, All] All

**Additional context:**

I  have found it is working when use plugin [`vite-plugin-iso-import`](https://www.npmjs.com/package/vite-plugin-iso-import) 

```svelte
<!-- +layout.svelte -->
<script lang="ts">
  import { browser } from "$app/environment";
  // @ts-ignore
  import { defineComponents } from "@tylertech/forge?client";
  if (browser) {
    defineComponents();
  }
</script>

<slot></slot>

```

**Comment by DRiFTy17** [comment]
The problem here is that when Vite is building your application it is running the SvelteKit compiler in a CJS environment in node. This is due to the fact that SvelteKit doesn't currently provide an easy way for developers to bundle client-only libraries separately.

The workaround you're using is fine because it forces that code to only run on the client in a browser environment so that it has access to native module loading and other browser APIs.

Another alternative to this is to use `onMount()` to dynamically import the components when the Svelte component is mounted:
```javascript
<script>
    import { onMount } from 'svelte';
    onMount(async () => {
        await import('@tylertech/forge/esm/button');
    })
</script>
```

**Comment by DRiFTy17** [comment]
https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window
