### ISSUE TITLE
Auotcomplete option dropdown closes and will no re-open

### ISSUE THREAD

**Issue by mjew1900** [tyler-technologies-oss/forge#682]
**Describe the bug:**
The dropdown will disappear when clicking in the text input and not reappear until clicking out and back in, in which case the text you started typing gets lost.

**To Reproduce:**
1. Click in the text input
2. Type a letter that would filter the dropdown
3. Click in the input, the dropdown closes and will not reopen until losing and regaining focus.

**Expected behavior:**
When clicking inside the text input, the dropdown should remain open

**Screenshots:**
![image](https://github.com/user-attachments/assets/0f514fc5-3d33-45d1-b07a-26f5124fa10a)

**Please complete the following information:**
 - Forge version: 3.0.0
 - I have searched existing issues before creating this report? Y
 - Browser: All
 - Platform: Desktop
 - OS: Windows

**Additional context:**
Problem can be observed in the demo documentation
https://forge.tylerdev.io/main/?path=/story/components-autocomplete--custom-options

**Comment by MikeMatusz** [comment]
Seems like the discrepancy here might be that the `autocomplete-adapter` listens for the `POPOVER_CONSTANTS.events.TOGGLE` event on the popover component's `anchorElement`, but the popover doesn't dispatch that event from it's anchor, it dispatches it from the `forge-popover` host.

I have verified locally that changing `setDismissListener` to add the listener directly to `dropdownElement` instead of `dropdownElement.anchorElement` ([here](https://github.com/tyler-technologies-oss/forge/blob/main/src/lib/autocomplete/autocomplete-adapter.ts#L153)) seems to fix the problem, but just wanted to confirm that this is indeed an issue with the autocomplete expectations, and not that the popover _should_ be emitting that event from the anchor.
